name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "adopt@1.11"

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Set header
        run: sed -i -e 's/internal.getString("application.iaah")/"${{ secrets.IAAH }}"/' common/core/src/main/scala/com/nulabinc/backlog/migration/common/conf/BacklogConfiguration.scala

      - name: Check format
        run: |
          mkdir -p dist
          sbt -no-colors checkAll > dist/result.txt

      - name: Test
        run: 'sbt "testOnly com.nulabinc.*"'

      - name: Assembly
        run: |
          sbt assembly
          mkdir -p target/dist
          mv target/scala-2.13/*.jar target/dist

      - name: Upload jar file
        uses: actions/upload-artifact@v5
        with:
          name: backlog-migration-redmine
          path: target/dist
